################################################################################
# Filename    # date.inc
# Purpose     # Defines date version
# Copyright   # Copyright (C) 2011-2017 Luke A. Guest, David Rees.
################################################################################
VERSION_DATE="24/07/2017"
BUILD_DATE=$(date +%d/%m/%Y)

COPYRIGHT="Copyright (C) 2011-2017 Luke A. Guest, David Rees. All Rights Reserved."
